/* CASA ACTIVA PWA 1.3 — imágenes realistas locales para todos los ejercicios. */
const EXERCISE_IMAGES_MALE={"squat":[{"width":396,"height":960,"src":"./assets/squat_0.webp"},{"width":396,"height":960,"src":"./assets/squat_1.webp"}],"dbrow":[{"width":470,"height":935,"src":"./assets/dbrow_0.webp"},{"width":470,"height":935,"src":"./assets/dbrow_1.webp"}],"floorpress":[{"width":680,"height":500,"src":"./assets/floorpress_0.webp"},{"width":680,"height":500,"src":"./assets/floorpress_1.webp"}],"curl":[{"width":600,"height":960,"src":"./assets/curl_0.webp"},{"width":600,"height":960,"src":"./assets/curl_1.webp"}],"press":[{"width":404,"height":960,"src":"./assets/press_0.webp"},{"width":404,"height":960,"src":"./assets/press_1.webp"}],"rower":[{"width":680,"height":747,"src":"./assets/rower_0.webp"},{"width":680,"height":747,"src":"./assets/rower_1.webp"}],"bike":[{"width":546,"height":960,"src":"./assets/bike_0.webp"},{"width":546,"height":960,"src":"./assets/bike_1.webp"}],"elliptical":[{"width":651,"height":960,"src":"./assets/elliptical_0.webp"},{"width":651,"height":960,"src":"./assets/elliptical_1.webp"}],"bridge":[{"width":680,"height":341,"src":"./assets/bridge_0.webp"},{"width":680,"height":341,"src":"./assets/bridge_1.webp"}],"hammer":[{"width":247,"height":503,"src":"./assets/hammer_0.webp"},{"width":248,"height":503,"src":"./assets/hammer_1.webp"}],"deadbug":[{"width":519,"height":251,"src":"./assets/deadbug_0.webp"},{"width":519,"height":252,"src":"./assets/deadbug_1.webp"}],"calf":[{"width":247,"height":503,"src":"./assets/calf_0.webp"},{"width":248,"height":503,"src":"./assets/calf_1.webp"}],"hinge":[{"width":247,"height":508,"src":"./assets/hinge_0.webp"},{"width":248,"height":508,"src":"./assets/hinge_1.webp"}],"circles":[{"width":259,"height":508,"src":"./assets/circles_0.webp"},{"width":260,"height":508,"src":"./assets/circles_1.webp"}],"catcow":[{"width":495,"height":254,"src":"./assets/catcow_0.webp"},{"width":495,"height":254,"src":"./assets/catcow_1.webp"}],"wallpush":[{"width":575,"height":438,"src":"./assets/wallpush_0.webp"},{"width":575,"height":432,"src":"./assets/wallpush_1.webp"}],"birddog":[{"width":529,"height":442,"src":"./assets/birddog_0.webp"},{"width":529,"height":445,"src":"./assets/birddog_1.webp"}],"plank":[{"width":619,"height":438,"src":"./assets/plank_0.webp"},{"width":619,"height":439,"src":"./assets/plank_1.webp"}]};
const EXERCISE_IMAGES_FEMALE={"squat":[{"width":591,"height":434,"src":"./assets/female_squat_0.webp"},{"width":590,"height":434,"src":"./assets/female_squat_1.webp"}],"dbrow":[{"width":506,"height":495,"src":"./assets/female_dbrow_0.webp"},{"width":506,"height":495,"src":"./assets/female_dbrow_1.webp"}],"floorpress":[{"width":506,"height":400,"src":"./assets/female_floorpress_0.webp"},{"width":506,"height":400,"src":"./assets/female_floorpress_1.webp"}],"curl":[{"width":506,"height":623,"src":"./assets/female_curl_0.webp"},{"width":506,"height":623,"src":"./assets/female_curl_1.webp"}],"press":[{"width":504,"height":513,"src":"./assets/female_press_0.webp"},{"width":507,"height":513,"src":"./assets/female_press_1.webp"}],"rower":[{"width":607,"height":337,"src":"./assets/female_rower_0.webp"},{"width":607,"height":337,"src":"./assets/female_rower_1.webp"}],"bike":[{"width":607,"height":431,"src":"./assets/female_bike_0.webp"},{"width":607,"height":431,"src":"./assets/female_bike_1.webp"}],"elliptical":[{"width":607,"height":493,"src":"./assets/female_elliptical_0.webp"},{"width":607,"height":493,"src":"./assets/female_elliptical_1.webp"}],"bridge":[{"width":591,"height":406,"src":"./assets/female_bridge_0.webp"},{"width":590,"height":406,"src":"./assets/female_bridge_1.webp"}],"hammer":[{"width":504,"height":495,"src":"./assets/female_hammer_0.webp"},{"width":507,"height":495,"src":"./assets/female_hammer_1.webp"}],"deadbug":[{"width":761,"height":320,"src":"./assets/female_deadbug_0.webp"},{"width":762,"height":320,"src":"./assets/female_deadbug_1.webp"}],"calf":[{"width":504,"height":509,"src":"./assets/female_calf_0.webp"},{"width":507,"height":509,"src":"./assets/female_calf_1.webp"}],"hinge":[{"width":565,"height":450,"src":"./assets/female_hinge_0.webp"},{"width":568,"height":450,"src":"./assets/female_hinge_1.webp"}],"circles":[{"width":565,"height":465,"src":"./assets/female_circles_0.webp"},{"width":568,"height":465,"src":"./assets/female_circles_1.webp"}],"catcow":[{"width":565,"height":438,"src":"./assets/female_catcow_0.webp"},{"width":568,"height":438,"src":"./assets/female_catcow_1.webp"}],"wallpush":[{"width":591,"height":440,"src":"./assets/female_wallpush_0.webp"},{"width":590,"height":440,"src":"./assets/female_wallpush_1.webp"}],"birddog":[{"width":761,"height":313,"src":"./assets/female_birddog_0.webp"},{"width":762,"height":313,"src":"./assets/female_birddog_1.webp"}],"plank":[{"width":761,"height":369,"src":"./assets/female_plank_0.webp"},{"width":762,"height":369,"src":"./assets/female_plank_1.webp"}]};
const IMAGE_PHASES={"squat":["Preparación de pie","Descenso controlado"],"dbrow":["Brazos extendidos","Codos hacia atrás"],"floorpress":["Preparación: codos apoyados","Empuje: brazos arriba"],"curl":["Barra abajo","Flexión de codos"],"press":["Pesas junto a los hombros","Empuje hacia arriba"],"rower":["Recogida","Final del tirón"],"bike":["Pedalada · fase A","Pedalada · fase B"],"elliptical":["Zancada · fase A","Zancada · fase B"],"bridge":["Cadera apoyada","Elevación de la pelvis"],"hammer":["Brazos abajo, agarre neutro","Flexión de codo con agarre neutro"],"deadbug":["Preparación: brazos y piernas arriba","Extiende brazo y pierna contrarios"],"calf":["Pies apoyados","Talones elevados"],"hinge":["Posición de pie","Cadera atrás y tronco inclinado"],"circles":["Brazos abiertos · posición A","Brazos abiertos · posición B"],"catcow":["Espalda redondeada · gato","Pecho abierto · vaca"],"wallpush":["Brazos extendidos","Acerca el pecho a la pared"],"birddog":["Cuatro apoyos","Brazo y pierna contrarios extendidos"],"plank":["Preparación sobre antebrazos y rodillas","Mantén hombros, cadera y rodillas alineados"]};
function exerciseVisualModel(){try{return S?.profile?.visualModel==='female'?'female':'male';}catch{return 'male';}}
function imageSet(){return exerciseVisualModel()==='female'?EXERCISE_IMAGES_FEMALE:EXERCISE_IMAGES_MALE;}
function hasRealisticImage(id){return Object.hasOwn(imageSet(),id);}
function isLandscapeImage(id){const set=imageSet();return Object.hasOwn(set,id)&&set[id][0].width>set[id][0].height;}
function phaseLabel(id,phase){return IMAGE_PHASES[id]?.[phase?1:0]||(phase?'Movimiento / posición final':'Preparación / posición inicial');}
function visualNote(id){const model=exerciseVisualModel()==='female'?'mujer':'hombre';return `Imágenes realistas generadas con IA con modelo ${model}, no fotografías. Toca para ampliar. Pueden contener imprecisiones: prioriza los pasos escritos y adapta el recorrido si algo no resulta cómodo.`;}
function scene(id,phase=0,label=true){
 const set=imageSet();if(!Object.hasOwn(set,id))return schematicScene(id,phase,label);
 const n=phase?1:0,asset=set[id][n],model=exerciseVisualModel()==='female'?'femenino':'masculino';
 const alt=`${EX[id]?.name||id}: ${phaseLabel(id,n)}. Modelo ${model}; imagen generada con IA.`;
 return `<span class="exercise-svg realistic-scene ${label?'captioned':''} ${isLandscapeImage(id)?'landscape':''}" data-exercise="${id}" data-phase="${n}"><img src="${asset.src}" alt="${esc(alt)}" width="${asset.width}" height="${asset.height}" decoding="async" draggable="false">${label?`<span class="scene-cue">${esc(phaseLabel(id,n))}</span>`:''}</span>`;
}
