/* CASA ACTIVA PWA — generated by tools/update_cache.py; do not edit this file directly. */
'use strict';
const VERSION="1.2.0";
const BUILD="1.2.0-c0cd8c783293f1";
const ROOT=new URL(self.registration.scope);
// Namespace by app path: never remove caches belonging to other GitHub Pages apps.
const PREFIX='casa-activa-pwa:'+encodeURIComponent(ROOT.pathname)+':';
const CACHE=PREFIX+BUILD;
const FILES=[
 "./",
 "./index.html",
 "./styles.css",
 "./pwa.css",
 "./data.js",
 "./illustrations.js",
 "./realistic.js",
 "./app.js",
 "./pwa.js",
 "./manifest.webmanifest",
 "./assets/bike_0.webp",
 "./assets/bike_1.webp",
 "./assets/bridge_0.webp",
 "./assets/bridge_1.webp",
 "./assets/curl_0.webp",
 "./assets/curl_1.webp",
 "./assets/dbrow_0.webp",
 "./assets/dbrow_1.webp",
 "./assets/elliptical_0.webp",
 "./assets/elliptical_1.webp",
 "./assets/floorpress_0.webp",
 "./assets/floorpress_1.webp",
 "./assets/manifest.json",
 "./assets/press_0.webp",
 "./assets/press_1.webp",
 "./assets/rower_0.webp",
 "./assets/rower_1.webp",
 "./assets/squat_0.webp",
 "./assets/squat_1.webp",
 "./icons/apple-touch-icon.png",
 "./icons/icon-192.png",
 "./icons/icon-512.png",
 "./icons/icon.svg",
 "./icons/maskable-512.png"
];
const URLS=FILES.map(path=>new URL(path,ROOT).href);
const ALLOWED=new Set(URLS);

self.addEventListener('install',event=>{
 event.waitUntil((async()=>{
  try{
   const cache=await caches.open(CACHE);
   await cache.addAll(URLS.map(url=>new Request(url,{cache:'reload'})));
  }catch(error){
   // Leave the previous version intact if download, quota or network fails.
   await caches.delete(CACHE);throw error;
  }
  // Do not skipWaiting automatically: updates must not interrupt a workout.
 })());
});

self.addEventListener('activate',event=>{
 event.waitUntil((async()=>{
  const keys=await caches.keys();
  await Promise.all(keys.filter(key=>key.startsWith(PREFIX)&&key!==CACHE).map(key=>caches.delete(key)));
  await self.clients.claim();
 })());
});

async function getAsset(request,key){
 const cache=await caches.open(CACHE);
 const stored=await cache.match(key);
 if(stored)return stored;
 // Recovery when the browser has evicted some cache entries.
 const response=await fetch(request);
 if(response.ok&&response.type!=='opaque'){
  try{await cache.put(key,response.clone());}catch{/* No quota: keep the online response usable. */}
 }
 return response;
}

self.addEventListener('fetch',event=>{
 const request=event.request;
 if(request.method!=='GET')return;
 const url=new URL(request.url);
 if(url.origin!==ROOT.origin||!url.pathname.startsWith(ROOT.pathname))return;
 url.search='';url.hash='';
 const isHome=url.pathname===ROOT.pathname||url.pathname===new URL('index.html',ROOT).pathname;
 if(request.mode==='navigate'&&isHome){
  event.respondWith(getAsset(request,new URL('index.html',ROOT).href));return;
 }
 // Only app files in the pre-cache list. No personal backup files, APIs or external links.
 if(ALLOWED.has(url.href))event.respondWith(getAsset(request,url.href));
});

async function status(){
 const cache=await caches.open(CACHE);
 const keys=new Set((await cache.keys()).map(request=>request.url));
 return {version:VERSION,build:BUILD,offlineReady:URLS.every(url=>keys.has(url))};
}
self.addEventListener('message',event=>{
 if(event.data?.type==='ACTIVATE_UPDATE')event.waitUntil(self.skipWaiting());
 if(event.data?.type==='STATUS')event.waitUntil((async()=>{
  try{event.ports[0]?.postMessage(await status());}
  catch{event.ports[0]?.postMessage({version:VERSION,offlineReady:false});}
 })());
});
